= GSQ Geochemistry Data Exchange Model

== Specification

This repository contains the content of the https://www.business.qld.gov.au/industries/mining-energy-water/resources/geoscience-information/gsq[Geological Survey of Queensland's] Geochemistry Data Exchange Model: it's Specification, the technical model (schema) as well as validators for testing data according to the model.

This specification document is delivered online at here:

* https://kurrawong.github.io/gsq-geochem-spec/spec.html[GSQ GeoChem Spec]

To get started, to test data against this Specification and to access data examples, use the:

* https://kurrawong.github.io/gsq-geochem-portal/[Demo GSQ Geochemistry Data Portal]

== License & Rights

This respository's content is licensed for reusing using the https://creativecommons.org/licenses/by/4.0/[Creative Commons BY 4.0] license, a copy of the deed of which is in the LICENSE file.

Much of the content of this model is taken from other models from international standards, all of which are openly licensed.

For any novel parts of this work:

&copy; The State of Queensland (Department of Resources) 2023

== Contacts

*Geoscience Information Team* +
_Geological Survey of Queensland_ +
Department of Resources +
Government of Queensland +
Brisbane, QLD, Australia +
geological_info@resources.qld.gov.au

Technical model designer:

Nicholas Car of *KurrawongAI*, specialist IT company: https://kurrawong.ai