== Introduction

This section introduces the general domain of information modelling that we use for geochemistry observations and then describes the particular representation mechanism used. Following sections then detail the model itself and provide reference material and validators.

=== Conceptual

==== Observations & Measurements

Geochemistry data - results of chemical and other analyses of geological samples - is a type of _observations_ data: observations of the natural world that result in measured properties. The general-purpose standard we use for modelling _observations_ data is the ISO's _Observations & Measurements_ (O&M) <<ISO19156, ISO19156>>.

O&M separates aspects of an _observations_ scenario into distinct information elements in order to ditinguish between the thing observed, the act of observing and outputs from the observing act. An informal, high-level, view of the conceptual elements of O&M is given in <<om-high-level>>.

[#om-high-level]
.An informal, high-level, view of the conceptual elements of _Observations & Measurements_ (O&M) <<ISO19156, ISO19156>>.
image::../img/om-high-level.svg[O&M high-level,align="center"]

In <<om-high-level>>, an _Observation_, an event, _observes_ a _Property_ of a _Sample_ (could be a chunk of rock, or a soil sample) which is a sample of a _Feature_ (could be a rock unit) and _produces_ a _Result_ according to a _Procedure_ which is implemented by/in a Sensor. Detailed representations of the sub-elements of _Observation_, _Feature_, _Property_ and so on are all specified by the use of other models, such as the _Quantities Units Dimensions & Types_ model for _Result_ elements which include the actual value measured, the measurement units and so on.

=== Logical

==== SOSA

There are many implementations of the O&M conceptual model and the one used here is the _SOSA (Sensor, Observation, Sample, and Actuator)_ ontology <<SOSA, SOSA>> which realises the elements and relations of O&M as <<OWL2, OWL>> _Classes_ and _Properties_. Using an OWL logical model allows for the exchange of data in the <<RDF, RDF>> format (a physical model).

SOSA's _Classes_ and _Properties_ for the elements in <<om-high-level>> are given in <<sosa-overview>>.

[#sosa-overview]
.An informal overview diagram of the SOSA data model using ellipses for OWL classes and named arrows for OWL predicates
image::../img/sosa-overview.svg[SOSA Model Overview,align="center"]

In <<sosa-overview>>, you can see a class for each of the elements in <<om-high-level>> as well as additional classes for collections of Observation elements and the units of a Result.

==== Background Models

As mentioned in the section above, detailed modelling of aspects of O&M's main elements are undertaken by other models, therefore, to completely model geochemistry data, we need more than just SOSA: we need a profile of SOSA and several other models, the union of which forms our overall model.

These other models we call _background models_ to distinguish them from SOSA which is then our _foreground model_.

Our set of background models, which are all <<OWL2, OWL>> models are:

GeoSPARQL <<GSP>>:: for relating spatial objects to one another and to representations of their geometries

QUDT <<QUDT>>:: for describing the values, units and references of results

SKOS <<SKOS>>:: for describing the structure of reference vocabularies and the relations between concepts within them

schema.org <<SDO>>:: for many general-purpose classes and predicates

All the background models we use have obvious connection points to our SOSA foreground model. For example, GeoSPARQL contains _Feature_ & _Geometry_ classes and the _Feature_ class is a superset of SOSA's _Feature of Interest_ class, thus any SOSA _Feature of Interest_ is a GeosPARQL _Feature_ and may have a GeoSPARQL _Geometry_ associated with it. <<sosa-geosparql>> shows this relationship.

[#sosa-geosparql]
.An informal diagram showing how SOSA and GeoSPARQL are related to one another based on the _Feature_ & _Feature of Interest_ class relationship
image::../img/sosa-geosparql.svg[SOSA/GeoSPARQL,align="center",width="60%"]

The formal modelling of the following section relates SOSA foreground model classes to relevant background model classes using <<OWL2, OWL>> relations.

=== Physical & Exchange

The canonical "physical" implementations of this model - a specific file format for data storage or exchange - is the Resource Description Framework [<<RDF, RDF>>]. RDF used for the foreground model, all the background models and thus this model too.

RDF is the only form of data that can be directly validated against this model, thus any conformance claims to this model must be substantiated by applying this specificaiton's validators to RDF data. See <<Validation>> form more information.

There are other physical implementations of this model available that are convertable to RDF that may be used for geochemistry data exchange. See <<Data Formats>>.

==== RDF

RDF data can be serialised in multiple formats. The format we use here for definitions and examples is <<TURTLE, Turtle>>. The <<turtle-eg, turtle format example>> below shows a dummy geochemistry _Observation_ represented according to SOSA and serialised in RDF's Turtle format.

[#turtle-eg]
.Example SOSA data in RDF's Turtle format, for a single geochemistry `Observation` according to the SOSA Ontology <<SOSA, SOSA>>
[source,turtle]
----
PREFIX ex: <http://example.com/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX op: <https://linked.data.gov.au/def/observable-properties/>
PREFIX sdo: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ex:obs-1
    a sosa:Observation ;
    sosa:usedProcedure ex:procedure-b ;
    sosa:madeBySensor ex:sensor-c ;
    sosa:observedProperty op:amount-of-gold ;
    sosa:hasFeatureOfInterest ex:sample-d ;
    sosa:hadPhenomenonTime "2023-05-11"^^xsd:date ;
    sosa:hasResult
        ex:result-e ,
        ex:result-f ;
.

ex:procedure-b
    a skos:Concept ;
    skos:prefLabel "Procedure B" ;
    skos:definition "A method for assessing the amount of gold in a sample" ;
.

ex:sensor-c
    a skos:Concept ;
    skos:prefLabel "Sensor C" ;
    skos:definition "A particular machine for assessing gold content in rock samples" ;
.

ex:sample-d
    a sosa:Sample ;
    sdo:name "Sample C" ;
    sdo:additionalType ex:soil-sample ;
    sdo:description "A soil sample from Sandy Creek" ;
    sdo:location "Zillmere Rock Store: Zone 4, Shelf N, Box 3" ;
    sosa:isSampleOf <https://linked.data.gov.au/dataset/qldgeofeatures/AnakieProvince> ;
.

ex:result-e
    sdo:value 0.027  ;
    sdo:unitCode <https://qudt.org/vocab/unit/PPM> ;
.

ex:result-f
    sdo:value 27.0 ;
    sdo:unitCode <https://qudt.org/vocab/unit/PPB> ;
.

<https://linked.data.gov.au/dataset/qldgeofeatures/AnakieProvince>
    a sosa:FeatureOfInterest , geo:Feature ;
    geo:hasGeometry [
        a geo:Geometry ;
        geo:asWKT "POLYGON((146.850699 -23.704934,146.850699 -20.863771,148.028386 -20.863771,148.028386 -23.704934,146.850699 -23.704934))" ;
    ] ;
.
----

In the <<turtle-eg, example data above>>, the object `ex:obs-1` is indicated as being a SOSA `Observation` (`... a sosa:Observation`), and a number of predicates are given for it, such as `sosa:hasFeatureOfInterest` which indicates the thing the observation is characterising predicates of, here the `Sample` `ex:sample-c`. The object `ex:sample-c` in turn has predicates such as `sosa:isSampleOf` indicating that it's a sample of `ex:sandy-creek` which, although no predicates are given, we understand to be a `Feature Of Interest` by virtue of the `Sample` object's relationship to it. The `Observation` is indicated to have taken place on the equipment of ID `ex:sensor-f`. This may be a class of system, rather than a particular instance of a system.

=== Profiles

Not all classes and predicates must be implemented to make valid data according to this model. For example, the `Result` of an `Observation` may have a `margin of error` indicated, but it need not and a dataset may indicate a `Feature Of Interest` with geospatial location but need not.

To know if data is valid according to this model, you need to apply a validator, given in the <<Validation>> to it. That section describes what the validators are, what they look for and tools that you can use to apply them.
