== Vocabularies

The model defined here depends on the use of multiple vocabularies to supply values for particular predicates. For example the objects indicated by <<sosa:observedProperty, observed property>> and <<sosa:usedProcedure, used procedure>> predicates should both be taken from vocabularies.

=== Referencing

When predicates indicate an object in a vocabulary, the reference is made by just quoting the IRI of the relevant <<skos:Concept, Concept>>, like this:

[source,turtle]
----
PREFIX ex: <http://example.com/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>

ex:obs-a
    a sosa:Observation ;
    sosa:observedProperty <https://linked.data.gov.au/def/observable-properties/amount-of-gold> ;
    sosa:usedProcedure ex:procedure-b ;
.
----

The Concept indicated by  `sosa:observedProperty` is one that already exists whereas the one indicated by `sosa:usedProcedure` does not: it's a dummy. The first Concept is indicated by its full IRI, the second by a namespace prefix-shortened form of its IRI.

=== Classes & Concepts

From this model's point of view, an object indicated by the <<sosa:usedProcedure, used procedure>> predicate is understood to be a `Procedure` object which may have special properties of its own, as indicated by <<SOSA, SOSA>>, such as `implementedBy` which tells a user which `Sensor` (s) actually use that Procedure. However, since this model requires no further information about objects indicated by `used procedure` etc. they are thought of as just  <<skos:Concept, Concept>> objects here.

=== Where

Vocabularies of Concepts are used for the values indicated by the following predicates in this model:

* <<sosa:usedProcedure, used procedure>>
* <<sosa:madeBySensor, made by sensor>>
* <<sosa:observedProperty, observed property>>
* <<sdo:unitCode, unit code>>
* <<sdo:keywords, keywords>>
* <<prov:hadRole, had role>>
* <<prov:agent, agent>>
* <<sdo:additionalType, additional type>>

=== Which

The particular vocabularies that must be used for the predicates listed above depend on which profile of this specification is used. Specific profiles require specific vocabularies and validate data according to them

See the <<Validation, Validation section>> for specifics.

=== Modelling

All vocabularies used with this model are expected to be <<SKOS, SKOS>> vocabularies, that is vocabularies formulated according to the SKOS model, which is one of the background models of this model.

SKOS vocabs allow concepts within them to:

* have a range of annotation properties - labels, definitions etc.
* relations to other concepts within that and other vocabs - they may be _broader_ or _narrower_ concepts than some others
* be sources from other vocabs, not just defined within the vocab listing them

SKOS vocabularies are published by many geological organisations, including the Geological survey of Queensland, who deliver their list of vocabularies online at:

* https://vocabs.gsq.digital

Vocabs can typically be extended via some governed mechanism and those of GSQ certainly can be.
