== Profiles

While many profiles of, and thus validators for, this model may be created, so far only one profile and validator have been created: the _GSQ Profile_, described below.

Profiles have separate identity to this specification so that data can indicate conformance specifically to them.

NOTE: All the resources needed for online validation of data according to all known profiles of this model are available at the https://geochem.dev.kurrawong.ai/[GSQ Geochemistry Data Portal].

=== GSQ Profile

The GSQ Profile of this model mandates certain predicates for classes of object and restricts which vocabularies may be used to supply values for predicates that indicate concepts, as described in the <<Where, Vocabularies: Where>> section above.

This profile's IRI is:

* https://linked.data.gov.au/def/geochem/gsq

The validator for this profile is available as a data file directly for download at:
* https://linked.data.gov.au/def/geochem/gsq

This validator is also pre-loaded in the https://geochem.dev.kurrawong.ai/[GSQ Geochemistry Data Portal].

==== Predicate Mandates

The following table lists classes of this model and gives the cardinality of predicates. Only classes that must be used are listed.

A cardinality of 1 means mandatory. 0+ means zero or more, 1+ one more, etc. 0-1 means zero or one.

[cols="2,3,3"]
|===
| Class | Predicate | Cardinality

| <<sosa:Observation, Observation>>                         | <<sosa:usedProcedure, used procedure>> | `1` unless in <<sosa:ObservationCollection, Observation Collection>>
|                                                           | <<sosa:madeBySensor, made by sensor>> | `1` unless in <<sosa:ObservationCollection, Observation Collection>>
|                                                           | <<sosa:observedProperty, observed property>> | `1` unless in <<sosa:ObservationCollection, Observation Collection>>
|                                                           | <<sosa:hasFeatureOfInterest, has feature of interest>> | `1` unless in <<sosa:ObservationCollection, Observation Collection>>
|                                                           | <<sosa:phenomenonTime, phenomenon time>> | `1` unless in <<sosa:ObservationCollection, Observation Collection>>
|                                                           | <<sosa:hasResult, has result>> | `1`
|                                                           | <<sdo:marginOfError, margin of error>> | `0-1`
|||
| <<sosa:Result, Result>>                                   | <<sdo:unitCode, unit code>> | `0-1` - not needed if `value` is a categorisation
|                                                           | <<sdo:value, value>>    | `1`
|                                                           | <<sdo:marginOfError, margin of error>> | `0-1`
|||
| <<sosa:Sample, Sample>>                                   | <<sosa:isSampleOf, is sample of>> | `0+`
|||
| <<sosa:ObservationCollection, Observation Collection>>    | <<sosa:hasMember, has member>> | `1+`
|                                                           | _...and any properties of <<sosa:Observation, Observation>>_ |
|||
| <<sosa:FeatureOfInterest, Feature Of Interest>>           | <<geo:hasGeometry, has geometry>> | `0-1`
|||
| <<geo:Geometry, Geometry>>                                | <<geo:asWKT, as WKT>> | `1`
|||
| <<dcat:Dataset, Dataset>>                                 | <<sdo:name, name>> | `1`
|                                                           | <<sdo:description, description>> | `1`
|                                                           | <<sdo:dateCreated, date created>> | `1`
|                                                           | <<sdo:dateModified, dateModified>> | `1`
|                                                           | <<sdo:keywords, keywords>> | `0+`
|                                                           | <<prov:qualifiedAttribution, qualified attribution>> | `1` per agent to be related to this Dataset
|||
| <<prov:Attribution, Attribution>>                         | <<prov:agent, agent>> | `1`
|                                                           | <<prov:hadRole, had role>> | `1`
|===

==== Vocab Restrictions

This profile requires that Concepts indicated by certain predicates come from specific vocabularies. The predicates and their required vocabularies are:

|===
| Predicate | Vocabulary

| <<sosa:usedProcedure, used procedure>>        | https://linked.data.gov.au/def/geochem-methods[Analytical methods for geochemistry]
| <<sosa:observedProperty, observed property>>  | https://linked.data.gov.au/def/observable-properties[Observable Properties]
| <<sdo:unitCode, unit code>>                   | https://linked.data.gov.au/def/geou[Geoscience Profile of QUDT Units], Geochemistry collection
| <<prov:hadRole, had role>>                    | https://data.idnau.org/pid/vocab/idn-role-codes[IDN Role Codes]
| <<prov:agent, agent>>                         | To be supplied by GSQ via the https://geochem.dev.kurrawong.ai/[GSQ Geochemistry Data Portal]
| <<sdo:additionalType, additional type>>       | When used on <<sosa:Sample, Sample>> objects: https://linked.data.gov.au/def/sample-type[Sample Types]
|===

Note that this profile does _NOT_ require that the predicate <<sosa:madeBySensor, made by sensor>> is used on the <<sosa:Observation, Observation>> class, thus no vocabulary is mandated for its use. It may be used but, if it is, the user may choose any vocabulary of Concepts to draw from useful to them.

==== Examples

The following example show _VALID_ and _INVALID_ data according to this GSQ Profile:

===== Eg 1: Valid

It contains all the required properties.

[#gsqp-eg-01]
.Valid data according to the GSQ Profile of this model
[source,turtle]
----
PREFIX ex: <http://example.com/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX op: <https://linked.data.gov.au/def/observable-properties/>
PREFIX sdo: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ex:obs-1
    a sosa:Observation ;
    sosa:usedProcedure ex:procedure-b ;
    sosa:madeBySensor ex:sensor-c ;
    sosa:observedProperty op:amount-of-gold ;
    sosa:hasFeatureOfInterest ex:sample-d ;
    sosa:hadPhenomenonTime "2023-05-11"^^xsd:date ;
    sosa:hasResult
        ex:result-e ,
        ex:result-f ;
.

ex:procedure-b
    a skos:Concept ;
    skos:prefLabel "Procedure B" ;
    skos:definition "A method for assessing the amount of gold in a sample" ;
.

ex:sensor-c
    a skos:Concept ;
    skos:prefLabel "Sensor C" ;
    skos:definition "A particular machine for assessing gold content in rock samples" ;
.

ex:sample-d
    a sosa:Sample ;
    sdo:name "Sample C" ;
    sdo:additionalType ex:soil-sample ;
    sdo:description "A soil sample from Sandy Creek" ;
    sdo:location "Zillmere Rock Store: Zone 4, Shelf N, Box 3" ;
    sosa:isSampleOf <https://linked.data.gov.au/dataset/qldgeofeatures/AnakieProvince> ;
.

ex:result-e
    sdo:value 0.027  ;
    sdo:unitCode <https://qudt.org/vocab/unit/PPM> ;
.

ex:result-f
    sdo:value 27.0 ;
    sdo:unitCode <https://qudt.org/vocab/unit/PPB> ;
.

<https://linked.data.gov.au/dataset/qldgeofeatures/AnakieProvince>
    a sosa:FeatureOfInterest , geo:Feature ;
    geo:hasGeometry [
        a geo:Geometry ;
        geo:asWKT "POLYGON((146.850699 -23.704934,146.850699 -20.863771,148.028386 -20.863771,148.028386 -23.704934,146.850699 -23.704934))" ;
    ] ;
.
----