name: Auto-buid HTML

on:
  push:
      branches:
          - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      working-directory: ./
      run: |
        echo "installing asciidoctor"
        sudo apt-get install asciidoctor ruby -y
        echo "Making deployment dir - docs/"
        mkdir docs

        echo "Add README to docs/"
        asciidoctor README.adoc -o docs/index.html
        echo "Add spec to docs/"
        asciidoctor spec/00-master.adoc -o docs/spec.html
        sed -i 's#../img/#img/#g' docs/spec.html

        echo "Add overview to docs/"
        asciidoctor overview/00-master.adoc -o docs/overview.html
        sed -i 's#../img/#img/#g' docs/overview.html

        # echo "Add images to docs/"
        cp -r img docs/

        # echo "Add model ontology RDF file to docs/"
        cp ont.ttl docs/ont.ttl

        # echo "Add Profile files to docs/"
        mkdir docs/profiles/core/
        cp profiles/core/validator.ttl docs/profiles/core/validator.ttl

        mkdir docs/profiles/gsq/
        cp profiles/gsq/validator.ttl docs/profiles/gsq/validator.ttl

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: docs